---
become_override: False
ocp_username: opentlc-mgr
silent: False


ocp4_workload_integreatly_user_count: 50
ocp4_workload_integreatly_tmp_dir: /tmp
ocp4_workload_integreatly_users_name_format: evals%02d

# If your workload needs customization options provide variables
# in a dictionary. The dictionary should be named "<role name>_defaults".
# So because this example workload is called "ocp-workload-example" the dictionary
# should be named "ocp_workload_example_defaults". Note that the dictionary can not
# include "-" characters, so replace all "-" with "_" instead.
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload. The overrides should be in a dictionary called
# "<role name>_vars".
#
# If there are any secrets that need to be passed (data that should not be in a
# public repo somewhere) you can specify another dictionary "<role name>_secrets".
#
# When the workload is executed the dictionary "<role name>" will be constructed from
# "<role name>_defaults" plus "<role name>_vars" (if defined) and "<role name>_secrets"
# (if defined).
#
# The logic in the workload should only use the dictionary "<role name>".
ocp4_workload_integreatly_defaults:
    dedicated_admin_username: "dedicated-admin"
    variable_1: "value 1"
    variable_2: "value 2"
    variable_secret: ""
    action: install
    namespace: redhat-rhmi-3scale
    seed_secret_name: system-seed
    tmp_dir: /tmp
    # default tenant details
    tenant_name: admin-tenant
    tenant_admin_user: admin
    tenant_admin_email: admin@example.com
    tenant_admin_password: Password1
    tenant_detail_secret_name: admin-tenant
    tenant_detail_secret_namespace: "redhat-rhmi-3scale"
    tenant_id_format: evals%02d-tenant
    # template references
    template_credential_secret: tenant-secret.json.j2
    template_tenant_resource: tenant.json.j2  


# Fuse
ocp4_workload_integreatly_fuse_namespace: redhat-rhmi-fuse
ocp4_workload_integreatly_fuse_operator_namespace: redhat-rhmi-fuse-operator
ocp4_workload_integreatly_fuse_instance_id_format: evals%02d-fuse
ocp4_workload_integreatly_fuse_template_operator_group: fuse-operator-group.json.j2
ocp4_workload_integreatly_fuse_template_subscription: fuse-subscription.json.j2
ocp4_workload_integreatly_fuse_template_syndensis_cr: fuse-syndesis-cr.json.j2
