---
# Implement your Post Workload deployment tasks here
# --------------------------------------------------
  
- name: get master host url from route
  shell: oc get route -n {{ namespace }} --selector=zync.3scale.net/route-to=system-master -o jsonpath='{.items[0].spec.host}'
  register: _action_get_threescale_master_host

- name: get master access token from secret
  shell: oc get secret {{ seed_secret_name }} -n {{ namespace }} -o jsonpath='{.data.MASTER_ACCESS_TOKEN}'
  register: _action_get_threescale_access_token

- set_fact:
    threescale_master_host: https://{{ _action_get_threescale_master_host.stdout }}
    threescale_master_token: "{{ _action_get_threescale_access_token.stdout | b64decode }}"

- name: debug
  debug: 
    msg: "found 3scale master host - {{ threescale_master_host }}"

- name: create 3scale tenants
  include_tasks: ../files/threescale/create-tenant.yml
  with_sequence: count="{{ user_count }}"
  when: action == "install"



# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload tasks completed successfully."
  when:
  - not silent|bool
  - not workload_shared_deployment|d(False)

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: post_workload tasks complete
  debug:
    msg: "Post-Software checks completed successfully"
  when:
  - not silent|bool
  - workload_shared_deployment|d(False)