---
# Set up the combined dictionary for the workload
# 
# To Do: Adjust the names of your dictionaries here
- name: Set up ocp4_workload_integreatly combined dictionary
  set_fact:
    ocp_workload_example: >-
      {{ ocp4_workload_integreatly_defaults
       | combine(ocp4_workload_integreatly_vars    | default( {} ),
                 ocp4_workload_integreatly_secrets | default( {} ), recursive=true )
      }}

# Implement your Workload removal tasks here
# ------------------------------------------

- name: get master host url from route
  shell: oc get route -n {{ namespace }} --selector=zync.3scale.net/route-to=system-master -o jsonpath='{.items[0].spec.host}'
  register: _action_get_threescale_master_host

- name: get master access token from secret
  shell: oc get secret {{ seed_secret_name }} -n {{ namespace }} -o jsonpath='{.data.MASTER_ACCESS_TOKEN}'
  register: _action_get_threescale_access_token

- set_fact:
    threescale_master_host: https://{{ _action_get_threescale_master_host.stdout }}
    threescale_master_token: "{{ _action_get_threescale_access_token.stdout | b64decode }}"

- name: debug
  debug: 
    msg: "found 3scale master host - {{ threescale_master_host }}"

- name: delete 3scale tenants
  include_tasks: delete-tenant.yml
  with_sequence: count="{{ lab_user_count }}"
  when: action == "uninstall" 



# Leave this as the last task in the playbook.
# --------------------------------------------
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
